# Generated by Django 5.2.15 on 2026-10-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_fix_missing_shop_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/addons/')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('available', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/flower_varieties/')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_varieties', to='shop.shop')),
            ],
            options={
                'verbose_name_plural': 'Flower varieties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/packagings/')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('available', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='BouquetComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_price_snapshot', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouquet_compositions', to='shop.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_compositions', to=settings.AUTH_USER_MODEL)),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bouquets.packaging')),
            ],
        ),
        migrations.CreateModel(
            name='BouquetCompositionAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_snapshot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bouquets.addon')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_links', to='bouquets.bouquetcomposition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('composition', 'addon'), name='unique_addon_per_composition')],
            },
        ),
        migrations.CreateModel(
            name='BouquetCompositionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bouquets.bouquetcomposition')),
                ('flower_variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bouquets.flowervariety')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('composition', 'flower_variety'), name='unique_flower_per_composition')],
            },
        ),
    ]
