# Generated by Django 6.0.6 on 2026-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAsistense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=7)),
                ('photo', models.ImageField(upload_to='asistenses/')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(max_length=1500)),
            ],
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(help_text='Enter the name of the flower', max_length=50),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='shopAsistense',
            field=models.ManyToManyField(to='products.shopasistense'),
        ),
    ]
