# Generated by Django 6.0.6 on 2026-06-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shopasistense_alter_productmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='shopAsistense',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(default='No named', help_text='Enter the name of the flower', max_length=50),
        ),
    ]
