# Generated by Django 5.2.15 on 2026-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_id_alter_shopasistense_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
