# Generated by Django 5.2.15 on 2026-07-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_seed_cities'),
        ('products', '0006_rename_created_productmodel_created_at_and_more'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopAsistense',
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='aviable',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='is_favourite',
            new_name='is_original',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowers', to='city.city'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='seller.seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
