# Generated by Django 5.2.15 on 2026-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_shopasistense_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_product_limit', models.PositiveIntegerField(default=3)),
                ('price_per_extra_product', models.PositiveIntegerField(default=5000)),
            ],
        ),
    ]
