# Generated by Django 5.2.15 on 2026-08-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productpricingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('sold', 'Sotildi')], default='active', max_length=10),
        ),
    ]
