# Generated by Django 5.2.15 on 2026-08-18 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productmodel_status'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='seller',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productpricingconfig',
            name='free_product_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
