# Generated by Django 5.2.15 on 2026-09-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productmodel_city_remove_productmodel_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricingconfig',
            name='free_product_limit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
