# Generated by Django 5.2.15 on 2026-09-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productpricingconfig_free_product_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSaleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_logs', to='products.productmodel')),
            ],
            options={
                'ordering': ['-sold_at'],
                'indexes': [models.Index(fields=['product', 'sold_at'], name='products_pr_product_4edcc2_idx')],
            },
        ),
    ]
