# Generated by Django 5.2.15 on 2026-09-20 05:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productsalelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sold_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.productmodel')),
            ],
            options={
                'indexes': [models.Index(fields=['starts_at', 'ends_at'], name='products_pr_starts__d03860_idx')],
            },
        ),
    ]
