# Generated by Django 5.2.15 on 2026-10-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productmodel_sold_count_productpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_type',
            field=models.CharField(choices=[('ready', 'Tayyor mahsulot'), ('custom_bouquet', "O'zi yasaydigan dasta")], db_index=True, default='ready', max_length=20),
        ),
    ]
