# Generated by Django 5.2.15 on 2026-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
