# Generated by Django 5.2.15 on 2026-10-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bouquets', '0001_initial'),
        ('products', '0014_productmodel_product_type'),
        ('shop', '0002_fix_missing_shop_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('delivering', 'Yetkazilmoqda'), ('completed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='new', max_length=12)),
                ('total_price', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=150)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bouquet_composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bouquets.bouquetcomposition')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productmodel')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bouquet_composition__isnull', True), ('product__isnull', False)), models.Q(('bouquet_composition__isnull', False), ('product__isnull', True)), _connector='OR'), name='orderitem_exactly_one_content_type')],
            },
        ),
    ]
