# Generated by Django 5.2.15 on 2026-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0014_productmodel_product_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orderitem_exactly_one_content_type',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('bouquet_composition__isnull', False), _negated=True), name='orderitem_exactly_one_content_type'),
        ),
    ]
