# Generated by Django 5.2.15 on 2026-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='paid_product_slots',
            field=models.PositiveIntegerField(default=0, help_text="Foydalanuvchi 5000 so'mga sotib olgan, hali ishlatilmagan qo'shimcha mahsulot slotlari"),
        ),
    ]
