# Generated by Django 5.2.15 on 2026-08-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_paid_product_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='shop_name',
        ),
    ]
