# Generated by Django 5.2.15 on 2026-09-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_seller_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='paid_product_slots',
            field=models.PositiveIntegerField(default=100, help_text="Foydalanuvchi 5000 so'mga sotib olgan, hali ishlatilmagan qo'shimcha mahsulot slotlari"),
        ),
    ]
