# Generated by Django 5.2.15 on 2026-09-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
         migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(
                max_length=10,
                choices=[('personal', 'Shaxsiy'), ('business', "Rasmiy do'kon")],
                default='personal',
            ),
        ),
    ]
