# Generated by Django 5.2.15 on 2026-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('home_top', 'Home (yuqori)'), ('search', 'Qidiruv'), ('product_detail', 'Mahsulot sahifasi')], default='home_top', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='target_type',
            field=models.CharField(choices=[('none', "Yo'q"), ('product', 'Mahsulot'), ('shop', "Do'kon"), ('url', 'Tashqi havola')], default='none', max_length=10),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['placement', 'is_active'], name='banners_ban_placeme_e61504_idx'),
        ),
    ]
