# Generated by Django 5.2.15 on 2026-10-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bouquets', '0001_initial'),
        ('products', '0014_productmodel_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('bouquet_composition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='bouquets.bouquetcomposition')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bouquet_composition__isnull', True), ('product__isnull', False)), models.Q(('bouquet_composition__isnull', False), ('product__isnull', True)), _connector='OR'), name='cartitem_exactly_one_content_type'), models.UniqueConstraint(fields=('user', 'product'), name='unique_product_per_user_cart')],
            },
        ),
    ]
